name: Build
on:
  pull_request:
  push:
    branches:
      - "master"
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            /var/lib/apt/lists
            /var/cache/apt/archives/**.deb
            !/var/lib/apt/lists/partial
            !/var/lib/apt/lists/lock
            !/var/cache/apt/archives/partial
            !/var/cache/apt/archives/lock
          key: ${{ runner.os }}-apt-v1
      - uses: lukka/get-cmake@latest
      - name: Setup APT packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends rpm
      - name: Build release
        run: ./build.sh pack
      - name: Upload to GitHub artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: "build/dist/"
      - name: Upload to GitHub release
        uses: xresloader/upload-to-github-release@v1
        with:
          file: "build/dist/*"
          tags: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
